const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const path=require('path'),fs=require('fs/promises'),dns=require('dns').promises,net=require('net'),ExcelJS=require('exceljs');
const UA='MapLeadsDesktop/1.0 (public business research)';
const C={restaurant:['["amenity"~"restaurant|cafe|fast_food"]'],hotel:['["tourism"~"hotel|guest_house|hostel"]'],pharmacy:['["amenity"="pharmacy"]'],clinic:['["amenity"~"clinic|hospital"]','["healthcare"]'],market:['["shop"~"supermarket|convenience|mall"]'],beauty:['["shop"~"beauty|hairdresser"]'],education:['["amenity"~"school|college|university|kindergarten"]'],bank:['["amenity"~"bank|atm"]'],construction:['["office"="construction_company"]','["craft"="builder"]','["shop"="building_materials"]'],real_estate:['["office"="estate_agent"]'],car_service:['["shop"="car_repair"]','["amenity"="car_wash"]'],fuel:['["amenity"="fuel"]'],all:['["name"]["amenity"]','["name"]["shop"]','["name"]["office"]','["name"]["tourism"]','["name"]["craft"]']};
let win,controller;
function create(){win=new BrowserWindow({width:1480,height:900,minWidth:1050,minHeight:680,backgroundColor:'#07111e',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.loadFile(path.join(__dirname,'renderer','index.html'));win.webContents.setWindowOpenHandler(({url})=>{if(/^https?:\/\//i.test(url))shell.openExternal(url);return{action:'deny'}})}
app.whenReady().then(create);app.on('window-all-closed',()=>process.platform!=='darwin'&&app.quit());
const progress=(percent,message)=>win&&!win.isDestroyed()&&win.webContents.send('search-progress',{percent,message});
const hp=()=>path.join(app.getPath('userData'),'history.json');
async function history(){try{return JSON.parse(await fs.readFile(hp(),'utf8'))}catch{return[]}}
async function addHistory(x){const h=await history();h.unshift(x);await fs.writeFile(hp(),JSON.stringify(h.slice(0,40),null,2))}
async function json(url,opt={}){const r=await fetch(url,{...opt,headers:{'User-Agent':UA,'Accept-Language':'az,en;q=.8',...(opt.headers||{})}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function geo(q,signal){const p=new URLSearchParams({q,format:'jsonv2',limit:'1',addressdetails:'1'}),a=await json(`https://nominatim.openstreetmap.org/search?${p}`,{signal});if(!a.length)throw Error('Ərazi tapılmadı. Adı daha dəqiq yaz.');const b=a[0].boundingbox.map(Number);return{name:a[0].display_name,bbox:`${b[0]},${b[2]},${b[1]},${b[3]}`}}
function query(box,cats,limit){const keys=cats.includes('all')?['all']:cats,filters=[...new Set(keys.flatMap(k=>C[k]||[]))];if(!filters.length)throw Error('Kateqoriya seç.');const lines=filters.flatMap(f=>['node','way','relation'].map(t=>`${t}${f}(${box});`)).join('\n');return`[out:json][timeout:90];(${lines});out center ${Math.max(limit*3,300)};`}
async function overpass(q,signal){let e;for(const u of['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'])try{const r=await fetch(u,{method:'POST',signal,headers:{'User-Agent':UA,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:q})});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}catch(x){if(x.name==='AbortError')throw x;e=x}throw Error(`Xəritə serveri cavab vermədi: ${e?.message||''}`)}
const first=(t,k)=>{for(const x of k)if(t[x])return String(t[x]).trim();return''};
function item(e){const t=e.tags||{},lat=e.lat??e.center?.lat??'',lon=e.lon??e.center?.lon??'',web=first(t,['contact:website','website','url']);return{id:`${e.type}/${e.id}`,name:first(t,['name','brand','operator'])||'Adsız obyekt',category:['amenity','shop','office','tourism','craft','healthcare'].find(k=>t[k])?`${['amenity','shop','office','tourism','craft','healthcare'].find(k=>t[k])}:${t[['amenity','shop','office','tourism','craft','healthcare'].find(k=>t[k])]}`:'business',phone:first(t,['contact:phone','phone','mobile','contact:mobile']),email:first(t,['contact:email','email']),website:web?(/^https?:\/\//i.test(web)?web:`https://${web}`):'',address:first(t,['addr:full','contact:address'])||[t['addr:street'],t['addr:housenumber'],t['addr:suburb'],t['addr:city'],t['addr:district']].filter(Boolean).join(', '),hours:t.opening_hours||'',latitude:lat,longitude:lon,osmUrl:`https://www.openstreetmap.org/${e.type}/${e.id}`,source:'OpenStreetMap'}}
function dedupe(a){const s=new Set;return a.filter(x=>{const k=`${x.name.toLowerCase()}|${x.phone.replace(/\D/g,'')}|${x.address.toLowerCase()}`;if(s.has(k))return false;s.add(k);return true})}
function privateIp(ip){if(net.isIPv4(ip)){const a=ip.split('.').map(Number);return a[0]===10||a[0]===127||a[0]===0||(a[0]===169&&a[1]===254)||(a[0]===172&&a[1]>=16&&a[1]<=31)||(a[0]===192&&a[1]===168)||(a[0]===100&&a[1]>=64&&a[1]<=127)||a[0]>=224}if(net.isIPv6(ip)){ip=ip.toLowerCase();return ip==='::1'||ip==='::'||/^(fc|fd|fe8|fe9|fea|feb)/.test(ip)}return true}
async function safe(u){const p=new URL(u);if(!/^https?:$/.test(p.protocol)||p.hostname==='localhost'||p.hostname.endsWith('.local'))throw Error('blocked');const a=await dns.lookup(p.hostname,{all:true});if(!a.length||a.some(x=>privateIp(x.address)))throw Error('blocked')}
function emails(h){return[...new Set((String(h).replace(/&#64;|&#x40;/gi,'@').replace(/&#46;|&#x2e;/gi,'.').match(/[\w.%+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[]).map(x=>x.toLowerCase()).filter(x=>!/(example\.|sentry\.|cloudflare\.)/.test(x)))]}
async function emailFromSite(site,signal){if(!site)return'';let base;try{base=new URL(site)}catch{return''}for(const u of[base.href,new URL('/contact',base).href,new URL('/elaqe',base).href,new URL('/about',base).href])try{await safe(u);const r=await fetch(u,{signal,redirect:'error',headers:{'User-Agent':UA,Accept:'text/html'}});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))continue;const h=(await r.text()).slice(0,1500000),m=emails(h);if(m.length)return m.slice(0,3).join(', ')}catch(e){if(e.name==='AbortError')throw e}return''}
async function enrich(a,signal){const q=a.filter(x=>!x.email&&x.website).slice(0,60);let n=0;async function worker(){while(q.length){const x=q.shift();x.email=await emailFromSite(x.website,signal);if(x.email)x.source='OSM + public website';progress(60+Math.round(++n/Math.max(n+q.length,1)*34),`Saytlarda e-poçt axtarılır: ${n}/${n+q.length}`)}}await Promise.all(Array.from({length:Math.min(3,q.length)},worker))}
ipcMain.handle('search-businesses',async(_,p)=>{controller?.abort();controller=new AbortController;const signal=controller.signal,start=Date.now();try{const area=String(p.area||'').trim(),limit=Math.min(Math.max(+p.limit||500,20),3000);if(area.length<2)throw Error('Ərazi adını yaz.');progress(5,'Ərazi tapılır...');const g=await geo(area,signal);progress(15,`Xəritə sorğulanır: ${g.name}`);const d=await overpass(query(g.bbox,p.categories||[],limit),signal);progress(50,`${d.elements?.length||0} obyekt emal edilir...`);let results=dedupe((d.elements||[]).map(item)).filter(x=>x.name!=='Adsız obyekt'||x.phone||x.email||x.website).slice(0,limit);if(p.enrichEmails)await enrich(results,signal);if(p.onlyWithContact)results=results.filter(x=>x.phone||x.email||x.website);const summary={area,resolvedArea:g.name,resultCount:results.length,withPhone:results.filter(x=>x.phone).length,withEmail:results.filter(x=>x.email).length,createdAt:new Date().toISOString(),durationMs:Date.now()-start};await addHistory(summary);progress(100,`${results.length} nəticə hazırdır.`);return{ok:true,location:{displayName:g.name},results,summary}}catch(e){return e.name==='AbortError'?{ok:false,cancelled:true,error:'Axtarış dayandırıldı.'}:{ok:false,error:e.message}}finally{controller=null}});
ipcMain.handle('cancel-search',()=>{controller?.abort();return{ok:true}});ipcMain.handle('get-history',history);ipcMain.handle('clear-history',async()=>{await fs.writeFile(hp(),'[]');return{ok:true}});ipcMain.handle('open-external',(_,u)=>/^https?:\/\//i.test(String(u))&&shell.openExternal(u));
const rows=a=>a.map((x,i)=>({No:i+1,Ad:x.name,Kateqoriya:x.category,Telefon:x.phone,Email:x.email,Sayt:x.website,Ünvan:x.address,'İş saatları':x.hours,Enlik:x.latitude,Uzunluq:x.longitude,'OSM linki':x.osmUrl,Mənbə:x.source}));
ipcMain.handle('export-results',async(_,p)=>{if(!p.results?.length)return{ok:false,error:'Nəticə yoxdur.'};const format=['csv','json','xlsx'].includes(p.format)?p.format:'csv',d=await dialog.showSaveDialog(win,{defaultPath:`map-leads-${new Date().toISOString().slice(0,10)}.${format}`,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(d.canceled)return{ok:false,cancelled:true};const r=rows(p.results);if(format==='json')await fs.writeFile(d.filePath,JSON.stringify(r,null,2));else if(format==='csv'){const h=Object.keys(r[0]),q=v=>`"${String(v??'').replace(/"/g,'""')}"`;await fs.writeFile(d.filePath,'\uFEFF'+[h.map(q).join(','),...r.map(x=>h.map(k=>q(x[k])).join(','))].join('\r\n'))}else{const w=new ExcelJS.Workbook(),s=w.addWorksheet('Bizneslər',{views:[{state:'frozen',ySplit:1}]}),h=Object.keys(r[0]);s.columns=h.map((x,i)=>({header:x,key:x,width:[6,28,22,20,28,32,42,20,14,14,42,22][i]||18}));s.addRows(r);s.getRow(1).font={bold:true};s.autoFilter={from:'A1',to:`L1`};await w.xlsx.writeFile(d.filePath)}return{ok:true,filePath:d.filePath}});
