export default class ActionPanel {
  constructor(scene, city){ this.scene=scene; this.city=city; this.container=scene.add.container(0,0).setDepth(10000).setScrollFactor(0).setVisible(false); this.items=[]; scene.scale.on("resize",()=>this.layout()); }
  clear(){ this.items.forEach(i=>i.destroy()); this.items=[]; }
  show(plot){ this.plot=plot; this.container.setVisible(true); this.render(); }
  render(){ this.clear(); const s=this.scene,w=s.scale.width,h=s.scale.height,p=this.plot; const panelW=Math.min(w-18,780), panelH=w<520?172:154; this.container.setPosition(w/2,h-panelH/2-12); const bg=s.add.graphics().fillStyle(0x020617,.78).fillRoundedRect(-panelW/2,-panelH/2,panelW,panelH,22).lineStyle(1,0xffffff,.1).strokeRoundedRect(-panelW/2,-panelH/2,panelW,panelH,22).lineStyle(1,0xd6b66a,.28).lineBetween(-panelW/2+22,-panelH/2+1,panelW/2-22,-panelH/2+1); const title=s.add.text(-panelW/2+20,-panelH/2+16,`${p.name} · ${p.zone}`,{fontFamily:"Inter, Arial, sans-serif",fontSize:w<520?"14px":"17px",color:"#f8fafc",fontStyle:"600"}); const details=s.add.text(-panelW/2+20,-panelH/2+43,`PRICE $${p.price.toLocaleString()}     STATUS ${p.status.replace("_"," ").toUpperCase()}     YIELD / MIN $${(p.income*p.level).toLocaleString()}`,{fontFamily:"Inter, Arial, sans-serif",fontSize:w<520?"10px":"12px",color:"#94a3b8"}); this.container.add([bg,title,details]); this.items.push(bg,title,details); this.buttonsFor(p).forEach((b,i)=>this.addButton(b,i,panelW,panelH)); }
  buttonsFor(p){ if(p.status==="empty") return ["Buy Land"]; if(p.status==="owned") return ["Build","Sell","Workers"]; if(p.status==="under_construction") return ["Workers","Sell"]; return ["Collect","Upgrade","Repair","Workers","Sell"]; }
  addButton(label,i,panelW,panelH){ const s=this.scene, w=s.scale.width, cols=w<520?3:7, bw=w<520?86:102, bh=34, gap=8, row=Math.floor(i/cols), col=i%cols, startX=-Math.min(panelW-36,cols*(bw+gap))/2; const x=startX+col*(bw+gap)+bw/2, y=panelH/2-52+row*(bh+8); const primary=label==="Collect"||label==="Buy Land"||label==="Build"; const bg=primary?"#d6b66a":label==="Sell"?"#7f1d1d":"#1e293b"; const color=primary?"#08111f":"#e5e7eb"; const t=s.add.text(x,y,label.toUpperCase(),{fontFamily:"Inter, Arial, sans-serif",fontSize:"11px",color,fontStyle:"600",backgroundColor:bg,padding:{x:12,y:9}}).setOrigin(.5).setInteractive({useHandCursor:true}); t.on("pointerdown",()=>this.act(label)); this.container.add(t); this.items.push(t); }
  act(label){ const id=this.plot.id; let ok=false, amount=0; if(label==="Buy Land") ok=this.city.buy(id); if(label==="Build") ok=this.city.build(id); if(label==="Upgrade") ok=this.city.upgrade(id); if(label==="Collect"){ amount=this.city.collect(id); ok=amount>0; if(ok) this.scene.animateCollect(this.plot,amount); } if(label==="Sell") ok=this.city.sell(id); if(label==="Repair"||label==="Workers") ok=true; this.plot=this.city.getPlot(id); this.render(); if(ok && (label==="Repair"||label==="Workers")) this.scene.toast(`${label} assigned`); }
  layout(){ if(this.plot) this.render(); }
}
