export default class ActionPanel {
  constructor(scene, city){ this.scene=scene; this.city=city; this.container=scene.add.container(0,0).setDepth(10000).setScrollFactor(0).setVisible(false); this.items=[]; scene.scale.on("resize",()=>this.layout()); }
  clear(){ this.items.forEach(i=>i.destroy()); this.items=[]; }
  show(plot){ this.plot=plot; this.container.setVisible(true); this.render(); }
  render(){ this.clear(); const s=this.scene,w=s.scale.width,h=s.scale.height,p=this.plot; this.container.setPosition(w/2,h-112); const panelW=Math.min(w-18,760), panelH=w<520?198:176; const bg=s.add.graphics().fillStyle(0x0f172a,.96).fillRoundedRect(-panelW/2,-panelH/2,panelW,panelH,20).lineStyle(1,0x475569,1).strokeRoundedRect(-panelW/2,-panelH/2,panelW,panelH,20); const title=s.add.text(-panelW/2+18,-panelH/2+14,`${p.name} · ${p.zone}`,{fontFamily:"Arial",fontSize:w<520?"15px":"18px",color:"#fff",fontStyle:"bold"}); const details=s.add.text(-panelW/2+18,-panelH/2+42,`Price: ${p.price}  Status: ${p.status.replace("_"," ")}  Income/min: ${p.income*p.level}`,{fontFamily:"Arial",fontSize:w<520?"12px":"14px",color:"#cbd5e1"}); this.container.add([bg,title,details]); this.items.push(bg,title,details); this.buttonsFor(p).forEach((b,i)=>this.addButton(b,i,panelW,panelH)); }
  buttonsFor(p){ if(p.status==="empty") return ["Buy Land"]; if(p.status==="owned") return ["Build","Sell","Workers"]; if(p.status==="under_construction") return ["Workers","Sell"]; return ["Collect","Upgrade","Repair","Workers","Sell"]; }
  addButton(label,i,panelW,panelH){ const s=this.scene, w=s.scale.width, cols=w<520?3:7, bw=96, bh=38, gap=8, row=Math.floor(i/cols), col=i%cols, startX=-Math.min(panelW-36,cols*(bw+gap))/2; const x=startX+col*(bw+gap)+bw/2, y=panelH/2-64+row*(bh+8); const t=s.add.text(x,y,label,{fontFamily:"Arial",fontSize:"13px",color:"#06111f",fontStyle:"bold",backgroundColor:label==="Collect"?"#86efac":label==="Sell"?"#fca5a5":"#fbbf24",padding:{x:12,y:10}}).setOrigin(.5).setInteractive({useHandCursor:true}); t.on("pointerdown",()=>this.act(label)); this.container.add(t); this.items.push(t); }
  act(label){ const id=this.plot.id; let ok=false, amount=0; if(label==="Buy Land") ok=this.city.buy(id); if(label==="Build") ok=this.city.build(id); if(label==="Upgrade") ok=this.city.upgrade(id); if(label==="Collect"){ amount=this.city.collect(id); ok=amount>0; if(ok) this.scene.animateCollect(this.plot,amount); } if(label==="Sell") ok=this.city.sell(id); if(label==="Repair"||label==="Workers") ok=true; this.plot=this.city.getPlot(id); this.render(); if(ok && (label==="Repair"||label==="Workers")) this.scene.toast(`${label} assigned`); }
  layout(){ if(this.plot) this.render(); }
}
